-- 경기도에 위치한 식품창고 목록 출력하기(Lev1) : IS NULL

SELECT A.WAREHOUSE_ID      AS WAREHOUSE_ID
     , A.WAREHOUSE_NAME    AS WAREHOUSE_NAME
     , A.ADDRESS           AS ADDRESS
     , CASE WHEN A.FREEZER_YN IS NULL THEN 'N'
            ELSE A.FREEZER_YN
       END                 AS FREEZER_YN
  FROM FOOD_WAREHOUSE A
 WHERE A.ADDRESS LIKE '경기도%'
 ORDER BY WAREHOUSE_ID