-- 성분으로 구분한 아이스크림 총 주문량(Lev2) : GROUP BY

SELECT B.INGREDIENT_TYPE   AS INGREDIENT_TYPE
     , SUM(A.TOTAL_ORDER)  AS TOTAL_ORDER
  FROM FIRST_HALF    A
     , ICECREAM_INFO B
 WHERE A.FLAVOR = B.FLAVOR
 GROUP BY INGREDIENT_TYPE