-- 자동차 대여 기록에서 대여중 / 대여 가능 여부 구분하기 (Lev3) : GROUP BY
WITH TMP_TBL0 AS (
SELECT A.*
     , CASE WHEN TO_DATE('20221016', 'YYYYMMDD') BETWEEN A.START_DATE AND A.END_DATE THEN '대여중'
            ELSE '대여 가능'
       END AS AVAILABILITY
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
)
-- SELECT * FROM TMP_TBL0 ORDER BY CAR_ID DESC, HISTORY_ID DESC;

SELECT A.CAR_ID          AS CAR_ID
     , MAX(AVAILABILITY) AS AVAILABILITY
  FROM TMP_TBL0 A
 GROUP BY A.CAR_ID
 ORDER BY CAR_ID DESC