-- 입양 시각 구하기(2)(Lev4) : GROUP BY

WITH TIME_HOUR AS (
-- 0시부터 23시까지
SELECT LEVEL - 1 AS HOUR
  FROM DUAL
 CONNECT BY LEVEL <= 24
)
--SELECT * FROM TIME_HOUR;

, ANIMAL_COUNT AS (
SELECT TO_CHAR(A.DATETIME, 'HH24') AS HOUR
     , COUNT(A.DATETIME) AS COUNT
  FROM ANIMAL_OUTS A
 GROUP BY TO_CHAR(A.DATETIME, 'HH24')
)
-- SELECT * FROM ANIMAL_COUNT;

SELECT A.HOUR
     , NVL(B.COUNT, 0) AS COUNT
  FROM TIME_HOUR    A
     , ANIMAL_COUNT B
 WHERE A.HOUR = B.HOUR(+)
 ORDER BY A.HOUR