-- 즐겨찾기가 가장 많은 식당 정보 출력하기(Lev3) : GROUP BY

WITH TMP_TBL0 AS (
SELECT A.FOOD_TYPE    AS FOOD_TYPE
     , MAX(FAVORITES) AS FAVORITES
  FROM REST_INFO A
 GROUP BY A.FOOD_TYPE
)
-- SELECT * FROM TMP_TBL0;

SELECT A.FOOD_TYPE AS FOOD_TYPE
     , A.REST_ID   AS REST_ID
     , A.REST_NAME AS REST_NAME
     , A.FAVORITES AS FAVORITES
  FROM REST_INFO A
     , TMP_TBL0 B
 WHERE A.FOOD_TYPE = B.FOOD_TYPE
   AND A.FAVORITES = B.FAVORITES
 ORDER BY FOOD_TYPE DESC