-- 입양 시각 구하기(1)(Lev2) : GROUP BY
-- 9시를 09시로 표현해도 결과는 동일한 정답으로 체크함

SELECT CASE WHEN TO_CHAR(A.DATETIME, 'HH24') = '09' THEN '9'
            ELSE TO_CHAR(A.DATETIME, 'HH24')
       END               AS HOUR
     , COUNT(A.DATETIME) AS COUNT
  FROM ANIMAL_OUTS A
 WHERE TO_CHAR(A.DATETIME, 'HH24') >= '09'
   AND TO_CHAR(A.DATETIME, 'HH24') <= '19'
 GROUP BY TO_CHAR(A.DATETIME, 'HH24')
 ORDER BY TO_CHAR(A.DATETIME, 'HH24')