-- 카테고리 별 도서 판매량 집계하기(Lev3) : GROUP BY

SELECT A.CATEGORY    AS CATEGORY
     , SUM(B.SALES)  AS TOTAL_SALES
  FROM BOOK       A
     , BOOK_SALES B
 WHERE A.BOOK_ID = B.BOOK_ID
   AND TO_CHAR(B.SALES_DATE, 'YYYYMM') = '202201'
 GROUP BY A.CATEGORY
 ORDER BY CATEGORY