-- 과일로 만든 아이스크림 고르기(Lev1) : SELECT

SELECT A.FLAVOR
  FROM FIRST_HALF    A
     , ICECREAM_INFO B
 WHERE A.FLAVOR = B.FLAVOR
   AND A.TOTAL_ORDER > 3000
   AND B.INGREDIENT_TYPE = 'fruit_based'
 ORDER BY A.TOTAL_ORDER DESC