-- 조건에 맞는 도서 리스트 출력하기(Lev1) : SELECT

SELECT A.BOOK_ID                               AS BOOK_ID
     , TO_CHAR(A.PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
  FROM BOOK A
 WHERE TO_CHAR(PUBLISHED_DATE, 'YYYY') = '2021'
   AND A.CATEGORY = '인문'
 ORDER BY PUBLISHED_DATE