-- 5월 식품들의 총매출 조회하기(Lev2) : Join

SELECT A.PRODUCT_ID               AS PRODUCT_ID
     , A.PRODUCT_NAME             AS PRODUCT_NAME
     , SUM ( A.PRICE * B.AMOUNT ) AS TOTAL_SALES
  FROM FOOD_PRODUCT A
     , FOOD_ORDER   B
 WHERE A.PRODUCT_ID = B.PRODUCT_ID
   AND TO_CHAR(B.PRODUCE_DATE, 'YYYYMM') = '202205'
 GROUP BY A.PRODUCT_ID, A.PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC, PRODUCT_ID