-- 자동차 평균 대여 기간 구하기(Lev2) : String, Date

-- 제출된 정답
SELECT A.CAR_ID                                     AS CAR_ID
     , ROUND(AVG(A.END_DATE - A.START_DATE + 1), 1) AS AVERAGE_DURATION
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
 GROUP BY A.CAR_ID
 HAVING AVG(A.END_DATE - A.START_DATE + 1) >= 7
 ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC

-- 사실은 이게 정답 : 13이 아니라 13.0으로 나와야 함
SELECT A.CAR_ID                                                          AS CAR_ID
     , TO_CHAR(ROUND(AVG(A.END_DATE - A.START_DATE + 1), 1), 'FM9990.0') AS AVERAGE_DURATION
  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
 GROUP BY A.CAR_ID
 HAVING AVG(A.END_DATE - A.START_DATE + 1) >= 7
 ORDER BY AVERAGE_DURATION DESC, CAR_ID DESC